### ISSUE TITLE
Phone country code may have 1..3 digits

### ISSUE THREAD

**Issue by vitalets** [Seia-Soto/clubhouse-api#10]
Currently `scripts/profile.js` [assumes](https://github.com/Seia-Soto/clubhouse-api/blob/2e205f0d5cefbfb08919ffdf1dcb07051e766afc/scripts/profile.js#L60) phone number has 2 only digit country code.
This is not always true. For example, Russia has +7 country code.
I suggest to add space to phone number format. That will allow to mark country code explicitly:
```diff
console.log('For example, let me assume that you have one Korean number: +82 10-1234-5678')
-  console.log('Then put: +821012345678')
+  console.log('Then put: +82 1012345678')

- const phoneNumberMatch = /\+(\d{2})(\d+)/.exec(phoneNumberInput)
+ const phoneNumberMatch = /\+(\d+)\s+(\d+)/.exec(phoneNumberInput)
```

**Comment by seia-soto** [comment]
Thank you for reporting! I resolved the issue.

**Comment by vitalets** [comment]
Wow, thanks!
Maybe we need also to strip extra space from `phoneNumber` variable later in code:
```diff
  quote('Please <press enter> if following information is correct and start authentication.')
  console.log(JSON.stringify({
    profile,
    user: {
-     phoneNumber,
+     phoneNumber.replace(/\s/g, ''),
      phoneNumberNation,
      phoneNumberUser
    }
  }, null, 2))
```

**Comment by seia-soto** [comment]
Ah, that's my fault that didn't look out side effects carefully. Really thank you for pointing out what's the problem and providing proper solution.

**Comment by vitalets** [comment]
You are welcome!
Thanks for your research and time!
