### ISSUE TITLE
HTTP proxy

### ISSUE THREAD

**Issue by 0x366** [Seia-Soto/clubhouse-api#12]
Hi! Thank you for great work!

Is it possible to use HTTP proxy to make requests?

I tied adding `options.agent = new HttpProxyAgent('my_proxy")` to `fetch` - but always getting `failed, reason: connect ECONNREFUSED` (though the proxy works fine). 

Maybe you have some suggestions how to do it ?

**Comment by seia-soto** [comment]
There is nothing tweaked from original node-fetch client, if you getting the issue by setting `agent`, it seems like your proxy or settings has a problem. Thank you for creating an issue but I hope you to ask only Clubhouse-related ones.

**Comment by seia-soto** [comment]
How to apply proxy settings in node-fetch is just what you did.
