### ISSUE TITLE
App flows - start screen, search and calendar 

### ISSUE THREAD

**Issue by 0x366** [Seia-Soto/clubhouse-api#16]
Thank you for such a great lib, its the best (at least for now). I have a question, regarding app flows (I don't have jailbroken phone to check it). Would be very glad, if you could answer:

1) When user open an app and get start screen - what request are done? Seems like there are at least two? I mean that screen
https://imgur.com/kUlRPOr

2) When you click search icon from start screen - the app makes request: `getSuggestedFollows`?

3) When you click calendar icon from start screen  - the app makes request: `getEvents`?

**Comment by seia-soto** [comment]
Via my iPhone I can inspect following requests when I open the app:

1. getOnlineFriends
2. checkForupdate
3. getChannels
4. getProfile
5. updateNotifications (with APN token which can be null)
6. recordActionTrails

When open search panel:

1. getTopics
2. getSuggestedFollows

When open events panel:

1. getEvents

Inspected with libFlex 4 on iPhone 10,4 14.4 RC.

**Comment by seia-soto** [comment]
It is really recommended to register with real iOS device because clubhouse is starting to ban users. Also, everything comes without any warranty.
