### ISSUE TITLE
[Bug] Cannot connect with the obtained token to Agora

### ISSUE THREAD

**Issue by tomaspavlin** [Seia-Soto/clubhouse-api#17]
Hi,

firstly thank you. I used your library to create a Clubhouse client https://github.com/tomaspavlin/clubhouse-client .

Everything worked perfectly but few days ago I got problems with connecting to Agora client. Since that, I did not manage to connect to Clubhouse audio stream. I would like to ask you if you have any suggestions what could be the reason. Queries to clubhouse server still looks to work fine, there is just the problem with connecting to Agora audio stream.

After calling joinChannel api, I try to connect to the Agora using:
```javascript
const options = {
  mode: 'rtc',
  codec: 'vp8'
}
this.agoraClient = AgoraRTC.createClient(options)

this.agoraKey = '938de3e8055e42b281bb8c6f69c21f78'

await this.agoraClient.join(
   this.agoraKey, channel, token, userId
)

// ...
// Playing the audio track
```

The `this.agoraClient.join` raises the following error:

```
{
  code: "CAN_NOT_GET_GATEWAY_SERVER"
  data: {retry: false}
  message: "AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status"
  name: "AgoraRTCException"
}
```

The arguments passed in `this.agoraClient.join` function looks correct:
```
0: "938de3e8055e42b281bb8c6f69c21f78"
1: "MEgBvN5k"
2: "006938de3e8055e42b281bb8c6f69c21f78IADJ8YVYb5NdcXWg+TZ9ZR2I0xMkcd+BW9Rq0sX1nF14DqxDSrp1FE6vEABP8GgACSg4YAEAAQAAAAAA"
3: 1848314487
```

What is weird is that it worked and it just stopped working few days ago. It is possible that this is rather agora issue than issue related to you library, but I still think that you could have some idea how to solve it.

**Comment by seia-soto** [comment]
It's nice to hear you created client which used my library and that's really interesting. So you mean the code work well before, right?

+ Please, consider closing and reopening the issue if possible. There is user ID and some sensitive data seems like test account or account related. Clubhouse starting banning users. (Old one will be deleted as soon as possible)

**Comment by seia-soto** [comment]
![image](https://user-images.githubusercontent.com/30369714/109079861-e8ab0100-7742-11eb-8c07-870650ccfad2.jpeg)

Confirmed that there's no changes in Info.plist of application bundle.

**Comment by tomaspavlin** [comment]
Yes, the code used to work well. I considered that it is because of the ban, but all clubhouse api works well.

I modified my user id before posting it to this issue.

**Comment by seia-soto** [comment]
It seems like streaming via other platform except for iOS was blocked.
Now I see that it's the time to hook again.

**Comment by tomaspavlin** [comment]
This is a traffic the client made with agora servers. Sensitive informations are modified in there. It could maybe help:

[agora-traffic.har.zip](https://github.com/Seia-Soto/clubhouse-api/files/6041742/agora-traffic.har.zip)

**Comment by seia-soto** [comment]
I'll reply you back with some tests done with my account after some schedules. Thank you for your details to check.

**Comment by yegorov-p** [comment]
> It seems like streaming via other platform except for iOS was blocked.
Yep. It started yesterday. Native Linux SDK is also blocked.

**Comment by yegorov-p** [comment]
It's really strange, but _some_ of my accounts are live again and work fine with linux SDK

**Comment by Joshfindit** [comment]
> It's really strange, but _some_ of my accounts are live again and work fine with linux SDK

Is it possible that the (very small) team is manually blocking non-iOS streaming?

**Comment by seia-soto** [comment]
> > It's really strange, but _some_ of my accounts are live again and work fine with linux SDK
> 
> Is it possible that the (very small) team is manually blocking non-iOS streaming?

It can be possible and they're mainly blocking users when they register their service automatically based on headers.

**Comment by yegorov-p** [comment]
well, i have an account that was banned (error 123) that didn't work for several days. And suddenly it started to work. It seems to be a temporary ban. Very strange.

**Comment by seia-soto** [comment]
It was quite easy to hook stuffs up to provide voice capacity, however it is mass now and not ready to open. I'll consider adding voice feature after thinking once again about its side-effects. Adding the feature is not determined, yet. It is because, there are many security holes about Clubhouse, and those holes can indirectly harm existing users.

Also, after considering some source-closing, I thought someone can think I am not open sourcing to divide non-iDevice users. However, I want to say that it's not true. There are many posts worrying about security hole on Clubhouse.

This is my state for open sourcing voice API(Agora iOS SDK) and I think we need to think one more chance to Clubhouse to protect existing users from being their voice recorded.

> Writing this state was done with mobile, so please understand even there are some English errors.

**Comment by tomaspavlin** [comment]
So if I want to connect to agora from JS without being blocked, is it enough to I use *agora-rtc-sdk-ng* and change http requests headers using proxy similarly as it is happening in your library, when you connect to clubhouse? Or is the solution more complicated than that.

**Comment by yegorov-p** [comment]
> I think we need to think one more chance to Clubhouse to protect existing users from being their voice recorded.

That's impossible. Once you have an unencrypted voice on your device, you can't protect it from recording. There's always a possibility to dumb record anything you want from audio jack.

**Comment by tomaspavlin** [comment]
I suppose that the potential security issue is to record voice by user that are not in the Clubhouse channel.  Otherwise I agree that recording voice in the channel you are in on your device will be always possible and should not be considered as security risk.

**Comment by yegorov-p** [comment]
> I suppose that the potential security issue is to record voice by user that are not in the Clubhouse channel.

If it's a public channel, than it's seems obvious that any person can join (and record it). It's currently possible to listen/record several channels simultaneously, by receiving several tokens for each channel, but it's not a security risk. You can do the same thing, using several iPhones, for example.

**Comment by Joshfindit** [comment]
> You can do the same thing, using several iPhones, for example.

They’ve actually started restricting multiple-device usage

**Comment by yegorov-p** [comment]
It doesn't really matter - fake number for sms costs several cents. Each invited user has at least 1 invite from the very beginning. You can reg as much fake account as you want and record as much channels as you want. And it's totally unbannable =)

**Comment by RallyCreatorCoins** [comment]
Any updates on this issue? :)

**Comment by seia-soto** [comment]
> Any updates on this issue? :)

There no updates, yet.

**Comment by elkarimareda** [comment]
i have same problem Error: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status

**Comment by seia-soto** [comment]
> It was quite easy to hook stuffs up to provide voice capacity, however it is mass now and not ready to open. I'll consider adding voice feature after thinking once again about its side-effects. Adding the feature is not determined, yet. It is because, there are many security holes about Clubhouse, and those holes can indirectly harm existing users.
> 
> Also, after considering some source-closing, I thought someone can think I am not open sourcing to divide non-iDevice users. However, I want to say that it's not true. There are many posts worrying about security hole on Clubhouse.
> 
> This is my state for open sourcing voice API(Agora iOS SDK) and I think we need to think one more chance to Clubhouse to protect existing users from being their voice recorded.
> 
> > Writing this state was done with mobile, so please understand even there are some English errors.

For people who see this later, please read my statement.

Also:

> > It seems like streaming via other platform except for iOS was blocked.
> > Yep. It started yesterday. Native Linux SDK is also blocked.

**Comment by chinfeng** [comment]
I guess the problem is clubhouse disabled access from agora-rtc-sdk-ng in their agora service. Maybe there is "user-agent" access control inside agora-rtc-sdk-ng sdk.

I use agora node sdk bypass this problem. Check my repo here: [https://github.com/chinfeng/ch-app](https://github.com/chinfeng/ch-app).

**Comment by callmearta** [comment]
I developed a desktop version using my fork of this repo which works using agora web rtc. feel free to check it

**Comment by chinfeng** [comment]
> I developed a desktop version using my fork of this repo which works using agora web rtc. feel free to check it

It is using agora-rtc-sdk, not ng sdk. I think agora web ng sdk cause the problem.

**Comment by seia-soto** [comment]
This issue will be closed as will not handle voice part here. Also, using any other frameworks isn't the permanent fix.
