### ISSUE TITLE
Follower/Following list not returning results

### ISSUE THREAD

**Issue by autumncarrot** [Seia-Soto/clubhouse-api#2]
Not sure if it's just me, but the Follower/Following list doesn't work as expected. I changed the get_followings to get_following and as mentioned in https://github.com/zhuowei/ClubhouseAPI/blob/main/doc/openapi.yaml and got it working but I'm not sure if it's any change on the server side now it's not returning results at all but does not pop up error message as well.

btw thanks for the great work

**Comment by autumncarrot** [comment]
My bad, should input numeric for ID not string

**Comment by seia-soto** [comment]
Also, there is my bad that didn’t describe request types. I’ll improve stuffs as you reported. Thank you! Don’t be rude at yourself.
