### ISSUE TITLE
[Bug] Cant run profile

### ISSUE THREAD

**Issue by chsnt** [Seia-Soto/clubhouse-api#21]
Install libs
`yarn install` or `npm install`

Try to run
`npm run profile`

Get error
```
clubhouse-api\node_modules\uuid\dist\esm-browser\index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'

```

**Comment by seia-soto** [comment]
You shouldn't use `npm` in this project because of PnP support. Also, your issue isn't reproducible from my side. Please attach more contexts such as Node.JS version or NPM version and your OS.

![image](https://user-images.githubusercontent.com/30369714/110037685-19fa8100-7d82-11eb-90a8-655fe83bd461.png)

`git clone https://github.com/Seia-Soto/clubhouse-api && cd clubhouse-api && yarn && yarn profile`

**Comment by seia-soto** [comment]
Tested also on NPM:

![image](https://user-images.githubusercontent.com/30369714/110037966-7a89be00-7d82-11eb-8957-d651251bb1eb.png)

**Comment by seia-soto** [comment]
Also, please keep the issue template for better help.

**Comment by seia-soto** [comment]
Issue will be closed and considered as user-side problem due to inactivity and leak of information.

**Comment by chsnt** [comment]
I'am tried to run profile by yarn 

`yarn profile`

But get error
```
Internal Error: clubhouse-api@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at J.getCandidates (D:\Projects\clubhouse-api\.yarn\releases\yarn-berry.cjs:2:347296)
    at n.getCandidates (D:\Projects\clubhouse-api\.yarn\releases\yarn-berry.cjs:2:336286)
    at D:\Projects\clubhouse-api\.yarn\releases\yarn-berry.cjs:2:357942
    at Module.w (D:\Projects\clubhouse-api\.yarn\releases\yarn-berry.cjs:2:417413)
    at C (D:\Projects\clubhouse-api\.yarn\releases\yarn-berry.cjs:2:357905)

```
![screenshot](https://i.imgur.com/xNumXA7.png)

Node.JS version: v13.6.0
NPM version: 7.6.0
OS: Windows 10

**Comment by seia-soto** [comment]
I don't know what you did but as I know, TypeScript 4.1.5 is installed not 4.2.2 from your screenshot shows.

[package.json](https://github.com/Seia-Soto/clubhouse-api/blob/master/package.json#L24)

![image](https://user-images.githubusercontent.com/30369714/110175500-31e70900-7e45-11eb-9ef4-7b9fe46ac127.png)

![image](https://user-images.githubusercontent.com/30369714/110175643-77a3d180-7e45-11eb-8849-b06d9e13e00a.png)

**Comment by seia-soto** [comment]
Try with master branch as I updated stuffs.
