### ISSUE TITLE
[Bug] app.searchUsers always returning 0 results

### ISSUE THREAD

**Issue by Joshfindit** [Seia-Soto/clubhouse-api#22]
**Describe the bug**

Results are always empty

**To Reproduce**

```
const app = new Client({ profile })
app.searchUsers(searchTerm).then(console.log)
```
Always returns `{ users: [], count: 0, next: 0, previous: 0, success: true }`, even if the search term is short and generic (like `food`)

**Expected behavior**
Some results

**profile.json:**
```javascript
{
  "apiRoot": "https://www.clubhouseapi.com/api",
  "userAgent": "clubhouse/304 (iPhone; iOS 14.4; Scale/2.00)",
  "userAgentStatic": "Clubhouse/304 CFNetwork/1220.1 Darwin/20.3.0",
  "appVersion": "0.1.28",
  "appBuild": "304",
  "agoraKey": "",
  "pubnubRoot": "https://clubhouse.pubnub.com",
  "pubnubPubKey": "",
  "pubnubSubKey": "",
  "pubnubSDK": "PubNFub-ObjC-iOS/4.15.11",
  "languages": "en-US",
  "locale": "en_US",
  "acceptLanguages": "en-US;q=1",
  "deviceId": "",
  "user": {
    "user_id": ,
    "name": "",
    "photo_url": "",
    "username": ""
  },
  "tokens": {
    "access": "",
    "auth": "",
    "refresh": ""
  },
  "verified": true,
  "_debug": {
    "req": {
      "update": {
        "has_update": false,
        "success": true
      },
      "auth": {
        "success": true,
        "is_blocked": false,
        "error_message": null
      },
      "login": {
        "success": true,
        "is_verified": true,
        "user_profile": {
          "user_id": ,
          "name": "",
          "photo_url": "",
          "username": ""
        },
        "auth_token": "",
        "refresh_token": "",
        "access_token": "",
        "is_waitlisted": false,
        "is_onboarding": false
      }
    }
  }
}%
```

**Comment by seia-soto** [comment]
Please, check if the update of application is available. I am not able to jailbreak and check what's going on right now because of 
financial matters.

**Comment by Joshfindit** [comment]
I checked the network request and noticed that my params were wrong. I should have instead been searching like `app.searchUsers({query: searchTerm}).then(console.log)`

Did a PR to add the ability to search like `app.searchUsers(searchTerm).then(console.log)`

**Comment by Joshfindit** [comment]
@Seia-Soto Best wishes to your financial matters resolving quickly.

**Comment by seia-soto** [comment]
Yes, that's the only matter why I cannot jailbreak and check stuffs. Thanks!

**Comment by callmearta** [comment]
I'm using this library and searchUsers works just fine. There's no bug in the library

**Comment by Joshfindit** [comment]
> I'm using this library and searchUsers works just fine. There's no bug in the library

As I mentioned above: 

> my params were wrong.
