### ISSUE TITLE
Club house web client

### ISSUE THREAD

**Issue by seovchinnikov** [Seia-Soto/clubhouse-api#24]
Hey guys!

I've implemented web browser client for ClubHouse (with supported audio features on Windows, macOS, linux).
I took this repo as a reference so I want to thank this repo's creator and all related contributors for its research.

Please find install instructions in README:

https://github.com/seovchinnikov/clubhouse-web

**Comment by Seia-Soto** [comment]
Sorry, but the issue pane is not the place for project advertisment. I'll close as this is not related to real issue.
