### ISSUE TITLE
Upload avatar

### ISSUE THREAD

**Issue by lafin** [Seia-Soto/clubhouse-api#3]
Hello. Thanks for your great work. 
How can I upload an avatar?

**Comment by seia-soto** [comment]
Oh, I didn't inspect that case, yet. Thank you for reporting.

I'll do it now and commit in an hour.

**Comment by seia-soto** [comment]
I implemented requested API function. However, I need to implement form-data myself to make stuff clear, because `FormData.prototype.setBoundary` method isn't documented and released in FormData v3, yet. You can use if you use master branch of FormData package.

> The update will be committed and v1.0.10 tag will be created soon.

**Comment by lafin** [comment]
Many thanks

**Comment by seia-soto** [comment]
I released new version, but you need to check more things about image format. Clubhouse seems not accepting other image formats except for JPEG now. I tested with photo which converted to png format from Photoshop, and didn't work. However, as you know, this is reverse engineering project, so you might check more cases.

![image](https://user-images.githubusercontent.com/30369714/107941483-1e2a4e80-6fcd-11eb-9156-f2ddafcb682a.png)

* Changed avatar from official app.
