### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by YogaSakti** [Seia-Soto/clubhouse-api#5]
hi, can you add an endpoint for the first registration (set username), I want to secure my username because I don't have an ios device

**Comment by seia-soto** [comment]
Thank you for reporting unsupported feature! I don't have any new account but it can be done with Twilio phone number. I'll look related stuffs but it can be take more time than I expected to make others safe. It will be implemented with in a day (I have some schedule to do now).

**Comment by seia-soto** [comment]
Closing as v1.0.12 released. I did sign up test manually with Twilio number.

> NOTHING COMES WITH WARRENTY! USE CAREFULLY.
