### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by tomaspavlin** [Seia-Soto/clubhouse-api#7]
I like your repo, good work! 💪

I ran your example code with no problem but what I have a problem with is using `initiateVoiceClient()` to listen voice in a room. I run the following code

```
app.debug(await app.initiateVoiceClient())
```

but it resulted to `ReferenceError: window is not defined`.

I modified the following line

https://github.com/Seia-Soto/clubhouse-api/blob/9b6760dc165c9317fffba9333e51939170db43b7/src/structures/voice.js#L10 

but similar error occured:

```
(node:15885) UnhandledPromiseRejectionWarning: /clubhouse-api/.yarn/cache/agora-rtc-sdk-ng-npm-4.3.0-2056a060aa-acea6e33c9.zip/node_modules/agora-rtc-sdk-ng/AgoraRTC_N-production.js:1
ReferenceError: window is not defined
    at /clubhouse-api/.yarn/cache/agora-rtc-sdk-ng-npm-4.3.0-2056a060aa-acea6e33c9.zip/node_modules/agora-rtc-sdk-ng/AgoraRTC_N-production.js:361:253
    at /clubhouse-api/.yarn/cache/agora-rtc-sdk-ng-npm-4.3.0-2056a060aa-acea6e33c9.zip/node_modules/agora-rtc-sdk-ng/AgoraRTC_N-production.js:24:99
    at Object.<anonymous> (/clubhouse-api/.yarn/cache/agora-rtc-sdk-ng-npm-4.3.0-2056a060aa-acea6e33c9.zip/node_modules/agora-rtc-sdk-ng/AgoraRTC_N-production.js:24:223)
    at Generator.next (<anonymous>)
```

Am I supposed to run the code in the browser to mitigate this issue or is there any other solution?

**Comment by seia-soto** [comment]
I am sorry to say that Agora Web SDKs are browser only and we need to make polyfill for Agora SDKs or port iOS SDK for more safety. However, you can create a custom client using Agora Electron SDK with high-performance native modules. (one of my private project)

Why I created `initiateVoiceClient` method is to divide browser-only module.

## References

- https://agoraio-community.github.io/AgoraWebSDK-NG/api/en
- https://github.com/AgoraIO/Electron-SDK

**Comment by tomaspavlin** [comment]
Thank you very much.

**Comment by seia-soto** [comment]
No problem! If you have any question, please feel free to ask again.

**Comment by tomaspavlin** [comment]
Since I am still not very experienced with NodeJS, I have one more question. What tool would you suggest for building code for browser where I will be able to test this? I am looking for a simple approach to run the `initiateVoiceClient` function.

**Comment by seia-soto** [comment]
I use Jest or Tap (test anything protocol) to test generally. However, this project isn't supposed to be tested or typed because there can be breaking changes and unexpected situations as the data source is not stable. I can help you as I can do but everything likely not to be clear at all. Also, testing should require your account login code and it isn't safe to test.

**Comment by tomaspavlin** [comment]
I probably did not explain myself properly. How do you run the `initiateVoiceClient` function to run it in a browser? By my understanding, yarn or node commands run the code by nodejs and not in the browser.

**Comment by seia-soto** [comment]
What you just said is correct, but in latest frontend frameworks like React, Vue, or Svelte stuffs, we use bundlers and many helper libraries to code. For instance, Babel does a lot of stuff to run modern codes in current web browser or even ES5(Internet Explorer). In case of using frontend frameworks, this module will be bundled automatically into your project by simply adding this module with package manager. However, if you don't use those frameworks, you need to create *build* for web browser with Webpack manually. The JavaScript ecosystem is really huge and also I didn't learn everything, yet, and learning everything is impossible. I want to provide one file for you but this project isn't ready to be shipped with umd build or other formats which can be run on browser. It cannot be done with one line.

## References

- http://rollupjs.org/guide/en/#quick-start

**Comment by tomaspavlin** [comment]
Thank you, I understand it much better now.

**Comment by seia-soto** [comment]
Sorry for late answer but hope it helped. I'll consider standalone browser bundle for future release.

**Comment by tomaspavlin** [comment]
Hi @Seia-Soto, I am sorry to interrupt you again, I have one more problem and a related question. What I tried was to create react app using `npx create-react-app`. But when I imported
```
import { Client, profiles } from 'clubhouse-api';
```

I got the following compile warnings:
```
Compiled with warnings

./node_modules/esm/esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/esm/esm.js
Module not found: Can't resolve 'internal/bootstrap/loaders' in '/my-react-app/node_modules/esm'
```

It resulted to the modules not imported. Is my approach to make the library running correct? Again, I am sorry for questions that are maybe stupid.

**Comment by seia-soto** [comment]
You're not stupid and also I don't think you're. I'll check it in few minute because I didn't use CRA for a long time.

**Comment by seia-soto** [comment]
@tomaspavlin For instance fix, you can do try importing `clubhouse-api/src/index.esm`.

**Comment by tomaspavlin** [comment]
Thank you, it solved the issue.

**Comment by tomaspavlin** [comment]
What do you mean when you suggest to use proxy in the readme file? I have a problem with CORS policy as I try to call clubhouse api from localhost. Is it actually possible to send the correct headers in the api when I run the library in web browser? Thank you!

**Comment by seia-soto** [comment]
That's why I recommend you to use proxy on web browser. You'll probably get banned if you call APIs from web browser and it isn't safe than you think.

**Comment by seia-soto** [comment]
So if you want to create web client you need to create following flow for user:

Web Browser - Internal API gateway stuffs - Clubhouse API

**Comment by tomaspavlin** [comment]
I made the AgoraRTC running in the browser and I managed to listen to the selected channel. I will create a repo with web client on top of your library. Thank you for your work and for your help.

**Comment by seia-soto** [comment]
No problem! Please, close issue if everything goes fine. I'm happy to listen your success.

Take care about COVID-19 and have a greate day 😉

**Comment by seia-soto** [comment]
Closing as the original issue and related problems are resolved. If you have additional question, please open new issue if related to my project.
